rust-embedded/rust-sysfs-gpio

Cargo.toml
examples/blinky.rs
examples/interrupt.rs
examples/poll.rs
src/lib.rs

This is done by doing something like the following:
```rust
let mut poller = try!(pin.get_poller());
loop {
match try!(poller.poll(1000) {
Some(value) { println!("Pin is now {}", value) },
None => { println!("No change after 1 second") },
});
}
```

core: add support for interrupts via epoll

---

README.md

With `sysfs-gpio` as dependecy name I got the following error
```
$ cargo build
Updating registry `https://github.com/rust-lang/crates.io-index`
no matching package named `sysfs-gpio` found (required by `gpio_test`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: *
```

readme: update dependency name in Cargo.toml

---

.travis.yml
README.md
examples/blinky.rs
src/lib.rs

Changes made during code review. All commits should be atomic EXCEPT for the change to use `no_run` in rust-doc. That change relies on the added `get_pin` method.

Review changes

---

examples/blinky.rs
examples/interrupt.rs
examples/poll.rs
src/error.rs
src/lib.rs

Having a single, library specific error type exposed allows consumers to easily compose errors within their application (eg using `std::convert::From` and `try!`).
This patch updates the public API which previously returned an `io::Result` to return a `Result<T, SysfsGpioError>`. `From` implementations are provided for `SysfsGpioError` so that the `try!` macro can be used the same way internally.
These changes are backwards incompatible since they change the return type of public APIs.

api: Export SysfsGpioError type

---

src/lib.rs

create did not work in 1.6 nightly, didn't check on stable releases
offtopic:
My fork's master branch also uses a patched nix, that works on 1.6 nightly, but doesn't work on rust 1.5 and prior versions: https://github.com/marjakm/rust-sysfs-gpio
The breakage is related to: https://github.com/rust-lang/rust/issues/29774
My nix changes have a pull request: https://github.com/carllerche/nix-rust/pull/210

derive debug for Pin and PinPoller, open file instead of creating in read_from_device_file

---

src/lib.rs

This is useful for users of these types in external
libraries who may want to be able to use these types in various
ways (for instance, I bumped into some isses with traits not
being implemented in gpio-utils).
Signed-off-by: Paul Osborne <osbpau@gmail.com>

core: derive additional traits for exposed types

---

.travis.yml

Was playing with a few items for rust-embedded-bot support
but this item is not necessary and prevents travis from
running tests on branches other than 'auto'.
CC @nastevens

travis: run ci on all branches

---

README.md

Now that we are generating docs for changes coming into
master, it is probably best to have docs that are up-to-date.
CC @nastevens

docs: fix link to rustdocs

---

README.md

according to https://doc.rust-lang.org/std/thread/fn.sleep_ms.html and
the use line above uses sleep. This fixes this for first time users of the library.

sleep_ms is deprecated since 1.6

---

.travis.yml
src/lib.rs

I encountered a couple of bugs in the library while working with an i.MX6 SoC using Yocto. First, the function `Pin::from_path` was not resolving my exported GPIO at `/var/run/gpio` because Yocto had made `/var/run` itself a symlink, and the previous logic only expanded symlinks at the end of the path. Second, once I had fixed the first issue, I was unable to using `Pin::from_path` because the fully expanded path with all symlinks resolved was not neatly `/var/run/gpio/gpio(\d+)`. Instead, it included a lot of other SoC paths i.e. `/sys/devices/soc0/soc.2/2000000.aips-bus/20a8000.gpio/gpio/gpio101`
The included commits resolve both issues.
CC @posborne

Improve from_file path handling

---

examples/blinky.rs
examples/interrupt.rs
src/lib.rs

Makes sense to use Clippy to check for common errors. This should make the code faster, and more idiomatic.

Fixed a bunch of clippy warnings and errors

---

src/lib.rs

Makes sense that small enums or a small structure (only a u64) can be copied directly using the `Copy` trait. This should [speed up](https://medium.com/@robertgrosse/how-copying-an-int-made-my-code-11-times-faster-f76c66312e0f) certain operations.

Added Copy to Pin and enums

---

Cargo.toml

Bumped version number so that latest changes can make it to crates.io.

Bumped version number

---

.travis.yml
CHANGELOG.md
Cargo.toml
src/lib.rs

The logic of extract_pin_from_path is too rigid, expecting GPIOs to only exist at the "/sys/class/gpio" path. The problem with this is that the kernel may actually symlink the directory in "/sys/class/gpio" to a chip or SOC-specific path, and the logic prior to extracting the pin from the path performs a canonicalization, breaking the assumption.
So, for example, the following is the output of a gpio on the board I'm working with, which fails with the current check:
root# readlink /var/run/gpio/hwid-0
/sys/class/gpio/gpio122
root# readlink /sys/class/gpio/gpio122
../../devices/soc0/soc/2000000.aips-bus/20a8000.gpio/gpiochip3/gpio/gpio122
This PR fixes the issue by relaxing the restrictions of extract_pin_from_path to only look for a final file component that looks like "gpioXXXX".
I also …

Relax extract pin from path

---

Cargo.toml
README.md

crates.io will render the file specified in the `readme` field in place
of the description, so use the latter as a short single-line
description instead.

Replace the `description` field with the readme

---

.travis.yml

Tested on my fork, in the branch 'travis' you can find the README badge pointing to my own Travis build where it states that it's passing.
Fixes #53.

Bump minimum rustc to 1.26.0

---

Cargo.toml

~Waiting on: https://github.com/nix-rust/nix/issues/1060#issuecomment-494627579~
See also: https://github.com/rust-embedded/linux-embedded-hal/pull/17
Patching to git source tested to be working

bump nix to 0.14 to fix compilation issues

---

README.md
src/lib.rs

Was getting an "Operation not permitted" and realized the example code wasn't setting the direction.
Actually, the use statement was already there, printing a friendly warning:
```
use sysfs_gpio::{Direction, Pin};
```
Thanks!

Add missing set_direction in main example.

---

.gitignore
examples/blinky.rs
examples/interrupt.rs
examples/poll.rs
examples/tokio.rs
src/error.rs
src/lib.rs

Most warnings were about deprecated fns, but some were about unused arguments in other platforms.
Two unused fn warnings remained, used only in `#[cfg(any(target_os = "linux", target_os = "android"))]` fns, and I'm not sure what to do about them:
`flush_input_from_file` and `get_value_from_file`
Thanks for your time!

Run rustfmt and fix warnings

---

.travis.yml

After finding the regression I fixed in #61 I was very surprised that travis managed to compile #60 just fine on macOS (stable) and tried building it on my machine (which failed). 
Then I realised that the config file was using `--features tokio` instead of `use_tokio`.

Fix feature name tokio->use_tokio in travis config

---

src/lib.rs

Apparently I've introduced a regression in #58 (sorry!) because I didn't run the tests with features (and travis didn't run as seen in https://github.com/rust-embedded/rust-sysfs-gpio/pull/59#issuecomment-593207289).
This fixes that regression by compiling `get_value_from_file` also when `feature = "use_tokio"`.
I also took the opportunity to use `?` instead of all remaining `try!()` macros.

Fix compilation with use_tokio feature

---

CHANGELOG.md
Cargo.toml
examples/blinky.rs
examples/tokio.rs
src/error.rs
src/lib.rs

Bumped tokio, mio and futures to recent versions. Took some inspiration from the previous gpio-cdev tokio work and also picked some parts from #60.
Not tested the mio parts but the tokio example (from #60) seems to be working.

Bump async dependencies

---

.github/bors.toml
.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
examples/blinky.rs
examples/interrupt.rs
examples/poll.rs
src/lib.rs

Release 0.6.0

---

.github/workflows/ci.yml
CHANGELOG.md
README.md

This gets CI back into a working state. However, while making these updates I noticed that https://github.com/actions-rs is no longer maintained and it throws a ton of warnings. I'm opening this PR so we can unblock #77 and will open separate issues to migrate repos using actions-rs over to https://github.com/dtolnay/rust-toolchain.

CI update + update MSRV to 1.65.0

---

CHANGELOG.md
src/error.rs

I'm not sure if this repository is still being maintained, but the crate is still very useful when working with older Linux kernels.
This PR adds a simple implementation for mapping this crate's custom error type to `std::io::Error`. Having this impl is useful when interacting with other functions that return `std::io::Result`.

Add conversion to io::Error

---

.github/CODEOWNERS
.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
LICENSE-MIT
README.md
src/lib.rs

The effective MSRV before this change is already 1.70 due to dependencies so I have made this official.
`nix` could be updated further but that needs some small changes due to the deprecation of some of the functions that we use but that would need more time than I have for this at the moment.

Fix codeowners + update dependencies + raise MSRV
